spring:
  redis:
    database: 1
    host: 124.223.111.168
    port: 6379
    password:
    timeout: 6000ms
    lettuce:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 10
        min-idle: 5
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 6000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
    dynamic:
      primary: master
      strict: true
      datasource:
        master:
          url: jdbc:mysql://124.223.111.168:3306/shansj?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: java_zt_user
          password: Ii!hr$@5jZG6

  # 上传文件大小限制
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB

# sql打印
logging:
  level:
    com.univ.customs.mapper: info
    com.alibaba.druid.pool.DruidAbstractDataSource.*: ERROR


# mybatis plus 配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID", 5: id_word d 字符串类型;
      id-type: ASSIGN_UUID
email4:
  toUser4: 398207657@qq.com
  ccUser4: 398207657@qq.com